# Generated by Django 2.2.5 on 2021-04-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='Mobile',
            field=models.CharField(max_length=12),
        ),
    ]
